auto_save: false
store_data: true
keep_prev: false

flags: null
labels: null
file_search: null
sort_labels: true
validate_label: null

# label_dialog
show_label_text_field: true
label_completion: startswith

epsilon: 11.0

shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+U
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S

  open_next: D
  open_prev: A

  zoom_in: Ctrl++
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  add_point: Ctrl+Shift+P
  create_polygon: Ctrl+N
  create_rectangle: Ctrl+R
  create_line: null
  create_point: null
  edit_polygon: Ctrl+J
  delete_polygon: Delete
  duplicate_polygon: Ctrl+D
  undo: Ctrl+Z
  undo_last_point: [Ctrl+Z, Backspace]
  edit_label: Ctrl+E
  edit_line_color: Ctrl+L
  edit_fill_color: Ctrl+Shift+L
