auto_save: false
display_label_popup: true
instance_label_auto_increment: true
store_data: true
keep_prev: false
logger_level: info

flags: null
label_flags: null
labels: null
file_search: null
sort_labels: true
validate_label: null

# main
flag_dock:
  show: true
  closable: true
  movable: true
  floatable: true
label_dock:
  show: true
  closable: true
  movable: true
  floatable: true
shape_dock:
  show: true
  closable: true
  movable: true
  floatable: true
file_dock:
  show: true
  closable: true
  movable: true
  floatable: true

# label_dialog
show_label_text_field: true
label_completion: startswith
fit_to_content:
  column: true
  row: false

epsilon: 10.0

shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+U
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S
  save_to: null
  delete_file: Ctrl+Delete

  open_next: [D, Ctrl+Shift+D]
  open_prev: [A, Ctrl+Shift+A]

  zoom_in: [Ctrl++, Ctrl+=]
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  add_point: Ctrl+Shift+P
  create_polygon: Ctrl+N
  create_rectangle: Ctrl+R
  create_circle: null
  create_line: null
  create_point: null
  create_linestrip: null
  edit_polygon: Ctrl+J
  delete_polygon: Delete
  duplicate_polygon: Ctrl+D
  undo: Ctrl+Z
  undo_last_point: [Ctrl+Z, Backspace]
  edit_label: Ctrl+E
  edit_line_color: Ctrl+L
  edit_fill_color: Ctrl+Shift+L
  toggle_keep_prev_mode: Ctrl+P
