auto_save: false
store_data: true

labels: null
sort_labels: true
validate_label: null
show_label_text_field: true

shortcuts:
  close: Ctrl+W
  open: Ctrl+O
  open_dir: Ctrl+U
  quit: Ctrl+Q
  save: Ctrl+S
  save_as: Ctrl+Shift+S

  open_next: D
  open_prev: A

  zoom_in: Ctrl++
  zoom_out: Ctrl+-
  zoom_to_original: Ctrl+0
  fit_window: Ctrl+F
  fit_width: Ctrl+Shift+F

  create_polygon: Ctrl+N
  edit_polygon: Ctrl+J
  delete_polygon: Delete
  duplicate_polygon: Ctrl+D
  undo: Ctrl+Z
  undo_last_point: [Ctrl+Z, Backspace]
  edit_label: Ctrl+E
  edit_line_color: Ctrl+L
  edit_fill_color: Ctrl+Shift+L
